- id: restore-message
  name: Restore commit message
  description: Restore commit message after an earlier commit was aborted
  language: python_venv
  entry: restore-message
  args: ['--mode=restore']
  stages: [prepare-commit-msg]

- id: prepare-message
  name: Prepare commit message
  description: Add prefix from feature branch to commit message
  language: python_venv
  entry: prepare-message
  stages: [prepare-commit-msg]

- id: save-message
  name: Save commit message
  description: Save commit message in case the commit gets aborted
  language: python_venv
  entry: restore-message
  args: ['--mode=save']
  stages: [commit-msg]

- id: check-message
  name: Check message formatting
  description: Ensure commit message has correct formatting between header and description
  language: python_venv
  entry: check-message
  stages: [commit-msg]

- id: console-logging
  name: Remove console logging
  description: Remove lines in JavaScript and TypeScript containing console logging.
  language: system
  entry: "sed  -E -e '/console\\.(log|trace|dir)/d' -i ''"
  types: [javascript, ts]
  stages: [commit]

- id: check-test
  name: Remove focus and ignore from tests
  description: Remove focus and ignore from tests in JavaScript and TypeScript.
  language: system
  entry: "sed -E -e 's/[fx](describe|it)\\(/\\1(/g' -i ''"
  types: [javascript, ts]
  files: \.spec\.(ts|js)$
  stages: [commit]

- id: ng-lint
  name: Execute ng lint
  description: Execute ng lint from the node_modules directory
  language: python_venv
  entry: check-ng-lint
  types: [ts]
  stages: [commit]

- id: properties-whitespace
  name: Remove whitespace around '=' in *.properties
  description: Remove whitespace around '=' in property files
  language: system
  entry: "sed -E -e 's/^([^=[:space:]]+)[[:space:]]*=[[:space:]]*/\\1=/g -i ''"
  # entry : "sed -i'' -E -e '/^([^=[:space:]]+)[[:space:]]*=[[:space:]]*/{s//\\1=/g;h};${x;/./{x;q1};x;q0}'"
  types: [java-properties]
  stages: [commit]
