## https://pre-commit.com
# pre-commit install --install-hooks
#
# Run hooks on repo:
# pre-commit run --all-files [hook-id]
#
# Update repos:
# pre-commit autoupdate
---
minimum_pre_commit_version: 2.4.0
default_language_version:
  python: python3
default_stages: [commit]
fail_fast: false
exclude: ^$
repos:
  - repo: https://github.com/boidolr/pre-commit-hooks
    rev: v2.8
    hooks:
#       - id: prepare-message
#         args: [--ignore-branch=master]
      - id: restore-message
      - id: format-message
      - id: spellcheck-message
      - id: console-debugger
      - id: console-logging
      - id: console-window
      - id: check-test
      - id: properties-whitespace
      - id: replace-tabs
        exclude: Makefile
#      - id: search-replace
#        args:
#        - '--search="\t"'
#        - '--replacement="    "'
      - id: ng-lint
        args: [--fix]
#      - id: optimize-image
#      - id: optimize-jpg
#      - id: optimize-png
#      - id: optimize-svg
#      - id: optimize-webp

  - repo: local
    hooks:
      - id: check-fail-message
        stages: [commit-msg]
        name: Check commit message for fail
        language: pygrep
        entry: fail

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: \.(java|groovy|properties|ts|js|scss|yaml)$
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--pattern=^release, --branch=develop]
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
