## https://pre-commit.com
# pre-commit install --install-hooks
#
# Run hooks on repo:
# pre-commit run --all-files [hook-id]
#
# Update repos:
# pre-commit autoupdate
---
minimum_pre_commit_version: 2.4.0
default_language_version:
  python: python3
default_stages: [commit]
fail_fast: false
exclude: ^$
repos:
  - repo: https://github.com/boidolr/commit-hooks
    rev: v3.5.2
    hooks:
      # - id: prepare-message
      #   args: [--ignore-branch=master]
      - id: restore-message
      - id: format-message
      - id: spellcheck-message
      - id: ts-no-debugger
      - id: ts-no-console
      - id: ts-no-window
      - id: ts-no-focus-ignore
      - id: properties-whitespace
      - id: replace-tabs
        exclude: Makefile
      # - id: search-replace
      #   args:
      #   - '--search="\t"'
      #   - '--replacement="    "'
      - id: ts-ng-lint
        args: [--fix]
      # - id: optimize-avif
      # - id: optimize-jpg
      # - id: optimize-png
      # - id: optimize-svg
      # - id: optimize-webp

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: \.(java|groovy|properties|ts|js|scss|yaml)$
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--pattern=^release, --branch=develop]
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        types: [yaml]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.15.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--configfile, .bandit.yaml]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: sync-dependencies
        name: Synchronize dependencies
        entry: make sync
        language: system
        files: ^(setup\.cfg|build/sync_versions\.py)$
        pass_filenames: false
      - id: run-tests
        name: Run tests
        entry: make test
        language: system
        always_run: true
        pass_filenames: false
