- id: restore-message
  name: Restore commit message
  description: Restore commit message after an earlier commit was aborted
  language: python
  entry: restore-message
  stages: [prepare-commit-msg]

- id: prepare-message
  name: Prepare commit message
  description: Add prefix from feature branch to commit message
  language: python
  entry: prepare-message
  stages: [prepare-commit-msg]

- id: spellcheck-message
  name: Check spelling of message
  description: Check spelling of message against known dictionary.
  language: python
  entry: spellcheck-message
  additional_dependencies: [autocorrect==2.1.2]
  stages: [commit-msg]

- id: format-message
  name: Check message formatting
  description: Ensure commit message has correct formatting between header and description
  language: python
  entry: format-message
  stages: [commit-msg]

- id: console-debugger
  name: Check console debugger statements (deprecated)
  description: Use ts-no-debugger instead
  language: pygrep
  entry: '\bdebugger\b'
  types: [text]
  files: \.(ts|js)$

- id: console-logging
  name: Check console logging (deprecated)
  description: Use ts-no-console instead
  language: pygrep
  entry: '\bconsole\.(?:log|info|trace|dir|warn|error)\b'
  types: [text]
  files: \.(ts|js)$

- id: console-window
  name: Check window access (deprecated)
  description: Use ts-no-window instead
  language: pygrep
  entry: '\bwindow\b'
  types: [text]
  files: \.(ts|js)$

- id: check-test
  name: Check focus & ignore from tests (deprecated)
  description: Use ts-no-focus-ignore instead
  language: pygrep
  entry: '\b[fx](?:describe|it)'
  types: [text]
  files: \.spec\.(ts|js)$

- id: ts-no-debugger
  name: Check console debugger statements
  description: Check for lines in JavaScript and TypeScript containing debugger statements.
  language: pygrep
  entry: '\bdebugger\b'
  types: [text]
  files: \.(ts|js)$

- id: ts-no-console
  name: Check console logging
  description: Check for lines in TypeScript containing console logging.
  language: pygrep
  entry: '\bconsole\.\('
  types: [ts]

- id: ts-no-window
  name: Check window access
  description: Check for lines in JavaScript and TypeScript containing window access.
  language: pygrep
  entry: '\bwindow\b'
  types: [ts]

- id: ts-no-focus-ignore
  name: Check use of focus and ignore of tests
  description: 'Forbid use of `fit()`, `xit()`, `fdescribe()` and `xdescribe()` test functions'
  language: pygrep
  entry: '\b(?:fit|xit|fdescribe|xdescribe)\s*\('
  types: [ts]

- id: ts-ng-lint
  name: Execute ng lint
  description: Execute ng lint from the node_modules directory.
  language: python
  entry: check-ng-lint
  types: [ts]

- id: ng-lint
  name: Execute ng lint (deprecated)
  description: Use ts-ng-lint instead
  language: python
  entry: check-ng-lint
  types: [ts]

- id: search-replace
  name: Search and replace patterns
  description: Search and replace given patterns.
  language: python
  entry: search-replace
  exclude_types: [binary]

- id: replace-tabs
  name: Replace tabs with spaces
  description: Replace tabs with spaces in files.
  language: python
  entry: replace-tabs
  exclude_types: [binary]

- id: optimize-image
  name: Optimize images (deprecated)
  description: Use type specific hooks instead
  language: python
  entry: optimize-image
  additional_dependencies: [pillow==8.0.0,scour==0.38.1.post1]
  files: \.(png|svg|webp|jpe?g)$

- id: optimize-jpg
  name: Optimize jpgs
  description: Check whether jpgs can be reencoded to decrease file size.
  language: python
  entry: optimize-jpg
  additional_dependencies: [pillow==8.0.0]
  types: [jpeg]

- id: optimize-png
  name: Optimize pngs
  description: Check whether pngs can be reencoded to decrease file size.
  language: python
  entry: optimize-png
  additional_dependencies: [pillow==8.0.0]
  types: [png]

- id: optimize-svg
  name: Optimize svgs
  description: Check whether svgs can be stripped to decrease file size.
  language: python
  entry: optimize-svg
  additional_dependencies: [scour==0.38.1.post1]
  types: [svg]

- id: optimize-webp
  name: Optimize webps
  description: Check whether webps can be reencoded to decrease file size.
  language: python
  entry: optimize-webp
  additional_dependencies: [pillow==8.0.0]
  types: [webp]

- id: properties-whitespace
  name: Remove whitespace in property files
  description: Remove whitespace around '=' in property files.
  language: python
  entry: search-replace
  args:
    - '--search="^([^=\s]+)\s*=\s*"'
    - '--replacement="\1="'
  types: [java-properties]
