- id: restore-message
  name: Restore commit message
  description: Restore commit message after an earlier commit was aborted
  language: python_venv
  entry: restore-message
  stages: [prepare-commit-msg]

- id: prepare-message
  name: Prepare commit message
  description: Add prefix from feature branch to commit message
  language: python_venv
  entry: prepare-message
  stages: [prepare-commit-msg]

- id: save-message
  name: Save commit message (deprecated)
  description: Save commit message in case the commit gets aborted (deprecated)
  language: system
  entry: echo
  stages: [commit-msg]

- id: spellcheck-message
  name: Check spelling of message
  description: Check spelling of message against known dictionary.
  language: python_venv
  entry: spellcheck-message
  additional_dependencies: [autocorrect==2.0.0]
  stages: [commit-msg]

- id: check-message
  name: Check message formatting (deprecated)
  description: Ensure commit message has correct formatting between header and description
  language: python_venv
  entry: format-message
  stages: [commit-msg]

- id: format-message
  name: Check message formatting
  description: Ensure commit message has correct formatting between header and description
  language: python_venv
  entry: format-message
  stages: [commit-msg]

- id: console-debugger
  name: Remove console debugger statements
  description: Remove lines in JavaScript and TypeScript containing debugger statements.
  language: system
  entry: "sed  -E -e '/debugger/d' -i ''"
  types: [text]
  files: \.(ts|js)$
  stages: [commit]

- id: console-logging
  name: Remove console logging
  description: Remove lines in JavaScript and TypeScript containing console logging.
  language: system
  entry: "sed  -E -e '/console\\.(log|info|trace|dir|warn)/d' -i ''"
  types: [text]
  files: \.(ts|js)$
  stages: [commit]

- id: console-window
  name: Remove window access
  description: Remove lines in JavaScript and TypeScript containing window access.
  language: system
  entry: "sed  -E -e '/window/d' -i ''"
  types: [text]
  files: \.(ts|js)$
  stages: [commit]

- id: check-test
  name: Remove focus & ignore from tests
  description: Remove focus and ignore from tests in JavaScript and TypeScript.
  language: system
  entry: "sed -E -e 's/[fx](describe|it)\\(/\\1(/g' -i ''"
  types: [text]
  files: \.spec\.(ts|js)$
  stages: [commit]

- id: ng-lint
  name: Execute ng lint
  description: Execute ng lint from the node_modules directory.
  language: python_venv
  entry: check-ng-lint
  types: [ts]
  stages: [commit]

- id: optimize-image
  name: Optimize images
  description: Check whether images can be reencoded to decrease file size.
  language: python_venv
  entry: optimize-image
  additional_dependencies: [pillow==7.2.0,scour==0.38]
  files: \.(png|jpe?g)$
  stages: [commit]

- id: properties-whitespace
  name: Remove whitespace in property files
  description: Remove whitespace around '=' in property files.
  language: system
  entry: "sed -E -e 's/^([^=[:space:]]+)[[:space:]]*=[[:space:]]*/\\1=/g' -i ''"
  types: [java-properties]
  stages: [commit]
