name: Publish release
on: create

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GIT_USER: github-actions

    steps:
      - name: Create release for tag
        uses: actions/github-script@v4.0.2
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.actor == 'boidolr'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repository = context.repo

            await github.repos.createRelease({
              owner: repository.owner,
              repo: repository.repo,
              tag_name: context.payload.ref,
            });
