name: Publish release
on: create

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release for tag
        uses: boidolr/actions/create-release@main
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          github.actor == 'boidolr'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          tag-name: "${{ github.ref }}"
