name: Automatic update
on:
  workflow_dispatch:
  schedule:
    - cron: "5 7 */7 * *"

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    env:
      CHANGE_BRANCH: github-action/pre-commit
      TARGET_BRANCH: main

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/python-pip-env

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pre-commit
          key: "${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}"

      - name: Update pre-commit
        run: |
          pip install -q pre-commit
          pre-commit autoupdate
          pre-commit run --all-files

      - name: Push pre-commit changes
        id: git-push
        uses: ./.github/actions/git-push
        with:
          message: "Update pre-commit config"
          branch: "${{ env.CHANGE_BRANCH }}"

      - name: Create pre-commit update pull request
        uses: actions/github-script@v5
        if: >
          steps.git-push.outputs.pushed-changes == 'true'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo
            const { CHANGE_BRANCH, TARGET_BRANCH } = process.env

            await github.rest.pulls.create({
              owner: repository.owner,
              repo: repository.repo,
              title: 'Update pre-commit config',
              head: CHANGE_BRANCH,
              base: TARGET_BRANCH,
            });
