name: PR

on: [pull_request_target]

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: boidolr/commit-hooks
          path: tool
          ref: main

      - uses: actions/checkout@v2
        with:
          path: repo
          ref: "${{ github.event.pull_request.head.ref }}"

      - uses: boidolr/actions/python-pip-env@main

      - run: |
          python tool/build/sync_versions.py repo/setup.cfg repo/.pre-commit-hooks.yaml

      - uses: boidolr/actions/git-push@main
        with:
          message: "Synchronize dependencies"
          branch: "${{ github.event.pull_request.head.ref }}"
          working-directory: repo

      - run: |
          pip install -q black
          black repo

      - uses: boidolr/actions/git-push@main
        with:
          message: "Format Python code with psf/black"
          branch: "${{ github.event.pull_request.head.ref }}"
          working-directory: repo
