name: PR

on: [pull_request_target]

jobs:
  script:
    runs-on: ubuntu-latest
    env:
      CODE_DIRECTORY: repo
      TOOL_DIRECTORY: tool
      TOOL_REPO: boidolr/commit-hooks
      TOOL_BRANCH: main
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "${{ env.TOOL_REPO }}"
          path: "${{ env.TOOL_DIRECTORY }}"
          ref: "${{ env.TOOL_BRANCH }}"

      - uses: actions/checkout@v2
        with:
          path: "${{ env.CODE_DIRECTORY }}"
          ref: "${{ github.event.pull_request.head.ref }}"

      - uses: "./${{ env.TOOL_REPO }}/.github/actions/python-pip-env"

      - run: |
          python "${{ env.TOOL_DIRECTORY }}"/build/sync_versions.py "${{ env.CODE_DIRECTORY }}"/setup.cfg "${{ env.CODE_DIRECTORY }}"/.pre-commit-hooks.yaml

      - uses: "./${{ env.TOOL_REPO }}/.github/actions/git-push"
        with:
          message: "Synchronize dependencies"
          branch: "${{ github.event.pull_request.head.ref }}"
          working-directory: "${{ env.CODE_DIRECTORY }}"

      - run: |
          pip install -q black
          black "${env.CODE_DIRECTORY}"

      - uses: "./${{ env.TOOL_REPO }}/.github/actions/git-push"
        with:
          message: "Format Python code with psf/black"
          branch: "${{ github.event.pull_request.head.ref }}"
          working-directory: "${{ env.CODE_DIRECTORY }}"
